server:
  port: 9090

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: esta_es_mi_compleja_clave_secreta

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: usuarios-service
              uri: http://usuarios-service:9091
              predicates:
                - Path=/usuarios/**

            - id: catalogo-productos
              uri: http://catalogo-service:9092
              predicates:
                - Path=/productos/**

            - id: catalogo-categorias
              uri: http://catalogo-service:9092
              predicates:
                - Path=/categorias/**

            - id: inventario-service
              uri: http://inventario-service:9093
              predicates:
                - Path=/inventarios/**

            - id: ventas-service
              uri: http://ventas-service:9094
              predicates:
                - Path=/ventas/**

            - id: pagos-service
              uri: http://pagos-service:9095
              predicates:
                - Path=/pagos/**

            - id: envios-service
              uri: http://envios-service:9096
              predicates:
                - Path=/envios/**

            - id: auth-service
              uri: http://auth-service:9097
              predicates:
                - Path=/auth/**    

            - id: promociones-service
              uri: http://promociones-service:9098
              predicates:
                - Path=/promociones/**

            - id: resenas-service
              uri: http://resenas-service:9099
              predicates:
                - Path=/resenas/**