spring.application.name=ventas-service

spring.profiles.active=dev

server.port=9094

spring.datasource.url=jdbc:mysql://localhost:3306/ventas_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.file.name=logs/ventas-service.log

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

api.usuario.exists=http://localhost:9091/usuarios/%d/exists

api.catalogo.exists=http://localhost:9092/productos/%d

api.inventario.disponible=http://localhost:9093/inventarios/producto/%d/disponible

api.inventario.descontar=http://localhost:9093/inventarios/producto/%d/descontar

api.usuario.email=http://localhost:9091/usuarios/email?email=%s