spring.application.name=pagos-service

server.port=9095

spring.datasource.url=jdbc:mysql://localhost:3306/pagos_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
logging.file.name=logs/pagos-service.log

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

api.venta.exists=http://localhost:9094/ventas/%d